{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "version-catalog",
    "version": "0.1.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-0.1.31.toml",
          "url": "version-catalog-0.1.31.toml",
          "size": 19952,
          "sha512": "b5719d5a18b8b3f6d89d51b9c848048c8d8834d0bb7e2d3855bda8137e84efc84984e52b95212c014f99033aa758b6899048fed37b089aeda927e392fef83e62",
          "sha256": "e5bca3a1fbdc4420afb778178e824031753f563148f6ff084009e53125ac8424",
          "sha1": "86cd1d68c59ef1b309b3770246a161d6aea83546",
          "md5": "41784a9a7492e0e6ac2aab87940817a6"
        }
      ]
    }
  ]
}
