{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.22.jar",
          "url": "gradle-0.1.22.jar",
          "size": 223871,
          "sha512": "ee8c52e4f85725f8f3ac61776102c16844a071598c2ccf2b0eefc33d9dca4c124a35264b62b15a045b5bbf55a9781f702731fac8c064dfe4236f0d6cef26b266",
          "sha256": "0953c88f853f5a2ae9c99c8bf38671c716c8b420acf5d77c3139e73ed8a4cbe7",
          "sha1": "36a910dc3f8169084038a394276ac7ecdf526cba",
          "md5": "ab58c9ae0cdd488806ba7626d2c7a915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.22.jar",
          "url": "gradle-0.1.22.jar",
          "size": 223871,
          "sha512": "ee8c52e4f85725f8f3ac61776102c16844a071598c2ccf2b0eefc33d9dca4c124a35264b62b15a045b5bbf55a9781f702731fac8c064dfe4236f0d6cef26b266",
          "sha256": "0953c88f853f5a2ae9c99c8bf38671c716c8b420acf5d77c3139e73ed8a4cbe7",
          "sha1": "36a910dc3f8169084038a394276ac7ecdf526cba",
          "md5": "ab58c9ae0cdd488806ba7626d2c7a915"
        }
      ]
    }
  ]
}
