{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "custom-link",
    "version": "0.1.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.27.jar",
          "url": "custom-link-0.1.27.jar",
          "size": 5952,
          "sha512": "df738098de5ae05e16ecf2783efd5c804cbd3a05f960f2b9614976f7443a81a8d1a5da8c0f8a310cc22ff67170aec2cc1739abddbb363e417024386c26a5470b",
          "sha256": "7af5814026733e603e2f0f849c906e5c4fd8360035aa9cb1c489e87b266d0f3b",
          "sha1": "3bb8d8fab1e9a9dfac4ba3bb82ac7691ed59b60a",
          "md5": "f51829d3434d517ec88809c22b32a2a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.1.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.1.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.27.jar",
          "url": "custom-link-0.1.27.jar",
          "size": 5952,
          "sha512": "df738098de5ae05e16ecf2783efd5c804cbd3a05f960f2b9614976f7443a81a8d1a5da8c0f8a310cc22ff67170aec2cc1739abddbb363e417024386c26a5470b",
          "sha256": "7af5814026733e603e2f0f849c906e5c4fd8360035aa9cb1c489e87b266d0f3b",
          "sha1": "3bb8d8fab1e9a9dfac4ba3bb82ac7691ed59b60a",
          "md5": "f51829d3434d517ec88809c22b32a2a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-link-0.1.27-sources.jar",
          "url": "custom-link-0.1.27-sources.jar",
          "size": 1767,
          "sha512": "4a66d33a2adabb725cdc14f8e7ca466f96201d962d30347dda4089dbd3bbe581e13794643054389762aa513965164947e122faeb321daa5d7d06d148406865a3",
          "sha256": "3354d05b8dd1a8ad13e8774c05ddb98d28049fdc6fcab3631b667fb13591821d",
          "sha1": "f47ca66b881c1cc88211265079ad773bef23d92f",
          "md5": "6ef13ac39adf177f8c50077fc8913c3c"
        }
      ]
    }
  ]
}
