{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.35.jar",
          "url": "gradle-0.1.35.jar",
          "size": 243133,
          "sha512": "e51c8bbfeeba9415a4a0cbf8542b631a2a5d640ac1ba18fec7b1d915fd1b975b60c73346b117213c69acdc9c6fba8f2e346577afc75a1c5bd2024743f406caf3",
          "sha256": "696cb9e9caf7f0fcab805176db5bc0255ae04ef0f0f3418445702499404c6a1f",
          "sha1": "3aaf4914bdc6d81f78c5c98695e09a704182ed00",
          "md5": "c34df39e9095d937cf9d6603c00a7fc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.35.jar",
          "url": "gradle-0.1.35.jar",
          "size": 243133,
          "sha512": "e51c8bbfeeba9415a4a0cbf8542b631a2a5d640ac1ba18fec7b1d915fd1b975b60c73346b117213c69acdc9c6fba8f2e346577afc75a1c5bd2024743f406caf3",
          "sha256": "696cb9e9caf7f0fcab805176db5bc0255ae04ef0f0f3418445702499404c6a1f",
          "sha1": "3aaf4914bdc6d81f78c5c98695e09a704182ed00",
          "md5": "c34df39e9095d937cf9d6603c00a7fc5"
        }
      ]
    }
  ]
}
