{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "hide-internal-api",
    "version": "0.1.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.41.jar",
          "url": "hide-internal-api-0.1.41.jar",
          "size": 7211,
          "sha512": "8e05bec781d14c2aacfbb364f34b9583a4123b015fe5b89645a588f0ca6d3c29abc8402c3839283a88daa7d2b7983ca6458c5cc5d127df33b0e7cd8bc6d238dd",
          "sha256": "3aab1c79cc1b6e8349c48106926477bee0fa497df43eaf3ce73714619e2b4959",
          "sha1": "63c8bba8cbef1db6d2d802c1811ea0c177ffdfd3",
          "md5": "e0cf7344bedec372533d1fc9634dada8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.2.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.2.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.41.jar",
          "url": "hide-internal-api-0.1.41.jar",
          "size": 7211,
          "sha512": "8e05bec781d14c2aacfbb364f34b9583a4123b015fe5b89645a588f0ca6d3c29abc8402c3839283a88daa7d2b7983ca6458c5cc5d127df33b0e7cd8bc6d238dd",
          "sha256": "3aab1c79cc1b6e8349c48106926477bee0fa497df43eaf3ce73714619e2b4959",
          "sha1": "63c8bba8cbef1db6d2d802c1811ea0c177ffdfd3",
          "md5": "e0cf7344bedec372533d1fc9634dada8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hide-internal-api-0.1.41-sources.jar",
          "url": "hide-internal-api-0.1.41-sources.jar",
          "size": 1882,
          "sha512": "fce8ed43f00a746db6a8c8f4a8b1d2cd292593aecaa177520335c900a0de724d16e5b64616c937958f76072c236f644ce878d8e74d649b5aa2e95f8fa4ea5068",
          "sha256": "8b5263fefcf8fc740562cf721688ae7f68aad90c0b86109172c1e9c5d04b4362",
          "sha1": "3b126ca828be49ab4b7b7e6373f5212dd956637b",
          "md5": "607f1d9081aaef9eefcd74f7018baffb"
        }
      ]
    }
  ]
}
