{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "hide-internal-api",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.21.jar",
          "url": "hide-internal-api-0.1.21.jar",
          "size": 7205,
          "sha512": "38c0170421f8686c7aad5750b571cdccb4fb1c24d32bd72eec5e6da8c4d12afde537b42375f73d4c0112da4ce2815294ce7cd6252d1c5b6776725776fc9d1476",
          "sha256": "8c2e791413e6ef2c7589703c7b3f4a510ac10fdea83383920b549a8442591334",
          "sha1": "2b41770806c49e4f3eca0a4e11a37a07940ded69",
          "md5": "951e6638d7b48393b7a77c9cb8192a5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.21.jar",
          "url": "hide-internal-api-0.1.21.jar",
          "size": 7205,
          "sha512": "38c0170421f8686c7aad5750b571cdccb4fb1c24d32bd72eec5e6da8c4d12afde537b42375f73d4c0112da4ce2815294ce7cd6252d1c5b6776725776fc9d1476",
          "sha256": "8c2e791413e6ef2c7589703c7b3f4a510ac10fdea83383920b549a8442591334",
          "sha1": "2b41770806c49e4f3eca0a4e11a37a07940ded69",
          "md5": "951e6638d7b48393b7a77c9cb8192a5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hide-internal-api-0.1.21-sources.jar",
          "url": "hide-internal-api-0.1.21-sources.jar",
          "size": 1882,
          "sha512": "2e4d84d45d4c6e3e608208b6540dc35dbb6cd5b57b3d342dfda38b77aef9f8a2584a2096f5f8399bd7e94b9c37b52472a3f55520251382cd212b10665be0b68c",
          "sha256": "6d38702d8170f1839ef0ecfb14428a349831770aca94717183c407e0df50cfa3",
          "sha1": "9a6b0e15d5f9223f66a18cc9faeffac40a53fd5d",
          "md5": "0cf11ab418c2360a09b8d73e60de816a"
        }
      ]
    }
  ]
}
