{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "annotation",
    "version": "0.1.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-0.1.41.jar",
          "url": "annotation-0.1.41.jar",
          "size": 2858,
          "sha512": "62a4622faa1ac8d810bac01ef26fcef5c3d058b2d7a90ab112fa738ea87abcb0a3cf30282415ca2d1818e479d11b9b64de1df0dc97429054911a3f4d26f87840",
          "sha256": "b952aa3844ce5426887dc35b4a500faeaade8ec1c6177f32ebd4d4d83b644c09",
          "sha1": "663fc1b616ef8dc8861db9fce2cb3b961c4cd974",
          "md5": "ef2b55377f44f5f18ece17d0ae5ff605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-0.1.41.jar",
          "url": "annotation-0.1.41.jar",
          "size": 2858,
          "sha512": "62a4622faa1ac8d810bac01ef26fcef5c3d058b2d7a90ab112fa738ea87abcb0a3cf30282415ca2d1818e479d11b9b64de1df0dc97429054911a3f4d26f87840",
          "sha256": "b952aa3844ce5426887dc35b4a500faeaade8ec1c6177f32ebd4d4d83b644c09",
          "sha1": "663fc1b616ef8dc8861db9fce2cb3b961c4cd974",
          "md5": "ef2b55377f44f5f18ece17d0ae5ff605"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-0.1.41-sources.jar",
          "url": "annotation-0.1.41-sources.jar",
          "size": 3635,
          "sha512": "82862cd1a31168c6ef46d8471a65804cd62433d751d6a3b249689977f4751ff9f70ee77c249c803714e39df453e968422922401158b551eaf5a208932a683579",
          "sha256": "53e0a113644ca23b62e0bbce4fb91925a6cf7c501445c240386929228521c76c",
          "sha1": "033110c6c421191f4f3e68f70a6b4d90cc325968",
          "md5": "d154f33d4ca55ed3a5c82ce4465a2437"
        }
      ]
    }
  ]
}
