{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.28.jar",
          "url": "gradle-0.1.28.jar",
          "size": 223891,
          "sha512": "a4c2178d62a58f9679a58fcc404a09045fa15a85d99e493c082400f06fb60e255c81d193a676dc3b60918291249c9e8efecbde51b6f20671a24f8dc96f49c5d4",
          "sha256": "7886866ae260f660daf6d9080237def5ed86964f2db69bc719e3b8f11d7b1131",
          "sha1": "bb9bd7ae9693e05cea2a840ad42a70f6eb1b80f4",
          "md5": "7756cd3a6b8d167013e68723727a04be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.28.jar",
          "url": "gradle-0.1.28.jar",
          "size": 223891,
          "sha512": "a4c2178d62a58f9679a58fcc404a09045fa15a85d99e493c082400f06fb60e255c81d193a676dc3b60918291249c9e8efecbde51b6f20671a24f8dc96f49c5d4",
          "sha256": "7886866ae260f660daf6d9080237def5ed86964f2db69bc719e3b8f11d7b1131",
          "sha1": "bb9bd7ae9693e05cea2a840ad42a70f6eb1b80f4",
          "md5": "7756cd3a6b8d167013e68723727a04be"
        }
      ]
    }
  ]
}
