{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.37.jar",
          "url": "gradle-0.1.37.jar",
          "size": 243139,
          "sha512": "9009804409f8dc451a784fdeddb6caab127720527187b2bfdb1acaa0eb9862d9fd2bcb0c0547ee58661a2fa739b680ee6169ebce650c3bcf55099921fe17f9a8",
          "sha256": "0633fcf491a61add5347b95819330b81e4063c2843f505c48793438d885c192b",
          "sha1": "24a2f2a26007e2cd8a464dad809c719c2aba3529",
          "md5": "f7c66cbac6be89fbc316287a96906443"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.33"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.37.jar",
          "url": "gradle-0.1.37.jar",
          "size": 243139,
          "sha512": "9009804409f8dc451a784fdeddb6caab127720527187b2bfdb1acaa0eb9862d9fd2bcb0c0547ee58661a2fa739b680ee6169ebce650c3bcf55099921fe17f9a8",
          "sha256": "0633fcf491a61add5347b95819330b81e4063c2843f505c48793438d885c192b",
          "sha1": "24a2f2a26007e2cd8a464dad809c719c2aba3529",
          "md5": "f7c66cbac6be89fbc316287a96906443"
        }
      ]
    }
  ]
}
