{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.45.jar",
          "url": "gradle-0.1.45.jar",
          "size": 293872,
          "sha512": "e50d3884a9b9356b2e027ea05989bb6760b4683855398395cedbaced66692d84332515451326aff8e263e357f0c6b7da1f2af367e2265ee8f49fdbb4c8d9ae31",
          "sha256": "e3d84345e7db09a920db41e74bf99e7dabe543e76cf2a159f7861fa2c20f8c8e",
          "sha1": "7bc7d3491fec40d31282e2e27aedbc7dcffed151",
          "md5": "231137c5edd0a6ef60a556d826552f63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.33"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.45.jar",
          "url": "gradle-0.1.45.jar",
          "size": 293872,
          "sha512": "e50d3884a9b9356b2e027ea05989bb6760b4683855398395cedbaced66692d84332515451326aff8e263e357f0c6b7da1f2af367e2265ee8f49fdbb4c8d9ae31",
          "sha256": "e3d84345e7db09a920db41e74bf99e7dabe543e76cf2a159f7861fa2c20f8c8e",
          "sha1": "7bc7d3491fec40d31282e2e27aedbc7dcffed151",
          "md5": "231137c5edd0a6ef60a556d826552f63"
        }
      ]
    }
  ]
}
