{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "custom-link",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.21.jar",
          "url": "custom-link-0.1.21.jar",
          "size": 5952,
          "sha512": "04f2dbfb0488e41a4fcea5edb805a90931d42c11be861d05819127a6014f0adf25844c04cc44653c0f4be8dfeb56bdc90968a2d6a3c901057fae0f7cdbca6b25",
          "sha256": "aaf3ed7d4df45464e9f37e4e7c6a459c36d9b5a4b38acdf8e87ca508e5f5486b",
          "sha1": "067c6f9600526c51225489f1fe50b2737b9fde25",
          "md5": "face6bbd96dd3a2b88ccbea2d96251e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.21.jar",
          "url": "custom-link-0.1.21.jar",
          "size": 5952,
          "sha512": "04f2dbfb0488e41a4fcea5edb805a90931d42c11be861d05819127a6014f0adf25844c04cc44653c0f4be8dfeb56bdc90968a2d6a3c901057fae0f7cdbca6b25",
          "sha256": "aaf3ed7d4df45464e9f37e4e7c6a459c36d9b5a4b38acdf8e87ca508e5f5486b",
          "sha1": "067c6f9600526c51225489f1fe50b2737b9fde25",
          "md5": "face6bbd96dd3a2b88ccbea2d96251e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-link-0.1.21-sources.jar",
          "url": "custom-link-0.1.21-sources.jar",
          "size": 1767,
          "sha512": "1c15673f3f2658c463634f7429c4d4eba78068ea9b1729739d5bac4a168239b69dda9b0cde1e38719a29dd95b1c0b68c8a14f3a8e7e283e2c5ce813511de9a16",
          "sha256": "1c73f0f9a7a0da195d3a29c26c8dc442dd2d5e0166980fb6be95ddea1fea1198",
          "sha1": "c8771b91406cb3e75a7d9cd23473d9e84092417e",
          "md5": "3b807b92016c6d839092c614593be80f"
        }
      ]
    }
  ]
}
