{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "annotation",
    "version": "0.1.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-0.1.44.jar",
          "url": "annotation-0.1.44.jar",
          "size": 2858,
          "sha512": "62a4622faa1ac8d810bac01ef26fcef5c3d058b2d7a90ab112fa738ea87abcb0a3cf30282415ca2d1818e479d11b9b64de1df0dc97429054911a3f4d26f87840",
          "sha256": "b952aa3844ce5426887dc35b4a500faeaade8ec1c6177f32ebd4d4d83b644c09",
          "sha1": "663fc1b616ef8dc8861db9fce2cb3b961c4cd974",
          "md5": "ef2b55377f44f5f18ece17d0ae5ff605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-0.1.44.jar",
          "url": "annotation-0.1.44.jar",
          "size": 2858,
          "sha512": "62a4622faa1ac8d810bac01ef26fcef5c3d058b2d7a90ab112fa738ea87abcb0a3cf30282415ca2d1818e479d11b9b64de1df0dc97429054911a3f4d26f87840",
          "sha256": "b952aa3844ce5426887dc35b4a500faeaade8ec1c6177f32ebd4d4d83b644c09",
          "sha1": "663fc1b616ef8dc8861db9fce2cb3b961c4cd974",
          "md5": "ef2b55377f44f5f18ece17d0ae5ff605"
        }
      ]
    }
  ]
}
