{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.32.jar",
          "url": "gradle-0.1.32.jar",
          "size": 243144,
          "sha512": "bfafe35d1c1fe32f6e9c3627a24ece290d526f4a9fdd3e79dc143398b90bd38af25abe2d731fc2da9b63663b3b0f462431caad51484f92d199e6f0400ab7b7d5",
          "sha256": "ad2f3dd82b1c6c4675fd9424b1bb5498814ef8de49f957d36226f9a7d68a86dc",
          "sha1": "57c44ab777e4f4e9044e1d26453582c96822a91a",
          "md5": "5e23677f50dab30c5c2965ce2312a660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.32.jar",
          "url": "gradle-0.1.32.jar",
          "size": 243144,
          "sha512": "bfafe35d1c1fe32f6e9c3627a24ece290d526f4a9fdd3e79dc143398b90bd38af25abe2d731fc2da9b63663b3b0f462431caad51484f92d199e6f0400ab7b7d5",
          "sha256": "ad2f3dd82b1c6c4675fd9424b1bb5498814ef8de49f957d36226f9a7d68a86dc",
          "sha1": "57c44ab777e4f4e9044e1d26453582c96822a91a",
          "md5": "5e23677f50dab30c5c2965ce2312a660"
        }
      ]
    }
  ]
}
