{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.36.jar",
          "url": "gradle-0.1.36.jar",
          "size": 243131,
          "sha512": "852ae849c49cd6e17acfbd84ec9556a64d5ec52bc8da676e014e06ad63e3c3ecacc3184a4ad56d49080830ed085ae085bc28a7be559cf243d1b2fe98f0571df0",
          "sha256": "c82caedeac09f843a66b8256925eec09667be7e00cc3b50b21c29bfe42f01376",
          "sha1": "a7893fe3c98a0356d80d9b277f48d1ff70f901e0",
          "md5": "0da0566f06314f5699c374b98a4305f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.36.jar",
          "url": "gradle-0.1.36.jar",
          "size": 243131,
          "sha512": "852ae849c49cd6e17acfbd84ec9556a64d5ec52bc8da676e014e06ad63e3c3ecacc3184a4ad56d49080830ed085ae085bc28a7be559cf243d1b2fe98f0571df0",
          "sha256": "c82caedeac09f843a66b8256925eec09667be7e00cc3b50b21c29bfe42f01376",
          "sha1": "a7893fe3c98a0356d80d9b277f48d1ff70f901e0",
          "md5": "0da0566f06314f5699c374b98a4305f1"
        }
      ]
    }
  ]
}
