{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "version-catalog",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-0.1.18.toml",
          "url": "version-catalog-0.1.18.toml",
          "size": 18972,
          "sha512": "61c9ab5cb055b9d9061fe1d82613ca5ec696a5c7677f806f93ee0055af0e8821a218e22297251748b5743e4f9ad0e4a4fe55dd272751c5751c07139d92653591",
          "sha256": "e037f4e684ae647e1185da90e1eaafb0d2e58d9df38f0e87444a1781cb8350dc",
          "sha1": "6f1f9b3984bccf7f2da9a123006cc8f4dc5795d1",
          "md5": "953db0202a12c3bdd256074dca57b54c"
        }
      ]
    }
  ]
}
