{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.44.jar",
          "url": "gradle-0.1.44.jar",
          "size": 293834,
          "sha512": "ac5741b36298a165aff334a4ea546225c240167d7c67b19e3fcd81985410e28ac0c4c667701bd0fed2d95fc6744cfae53afb445b9909cd51d4b58511fdb10b2e",
          "sha256": "f57ed60162a15724076209dfb6d7785707ef13d7e7c0c64794b14a8928003e2f",
          "sha1": "a8f95a6eafb4320b2c52bbddcce67a6e4947b04d",
          "md5": "97d8be44af14980024f789fa0abb3aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.3.6"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.33"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.44.jar",
          "url": "gradle-0.1.44.jar",
          "size": 293834,
          "sha512": "ac5741b36298a165aff334a4ea546225c240167d7c67b19e3fcd81985410e28ac0c4c667701bd0fed2d95fc6744cfae53afb445b9909cd51d4b58511fdb10b2e",
          "sha256": "f57ed60162a15724076209dfb6d7785707ef13d7e7c0c64794b14a8928003e2f",
          "sha1": "a8f95a6eafb4320b2c52bbddcce67a6e4947b04d",
          "md5": "97d8be44af14980024f789fa0abb3aae"
        }
      ]
    }
  ]
}
