{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "version-catalog",
    "version": "0.1.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-0.1.36.toml",
          "url": "version-catalog-0.1.36.toml",
          "size": 19907,
          "sha512": "4b6f65635710f078d2e5aec8d965d3bcb7c5e24a56ea398e946d702d0cbde6aa3c8a47cbe6d190bfbc7a50c0c621a2912b08aff5f017ba2fa4c025c5ebd64033",
          "sha256": "ec8153f4a677920cd89361d4ed78c149f7f2657f77607eefce3aab5a7c7dad26",
          "sha1": "643ee37c1c76ed0b5f2c35020e68651e9ac3786c",
          "md5": "0acdcaffed8fcb8f68ceae419d42ac56"
        }
      ]
    }
  ]
}
