{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.26.jar",
          "url": "gradle-0.1.26.jar",
          "size": 223895,
          "sha512": "42f67b73cf54eab7184095ce441e08cedf158249ff27c92b20d8656a4bef1e73f9d366aaaafb676586aa1999533218db0d769c7e359dd2f42e31608c0ebf9ea6",
          "sha256": "ec8fd76e1acccd6e293dc168707ed3e5f26138bbf74402a711a2dfaf05cc73a3",
          "sha1": "432a1094a8434351663ae8b203ef4734adf9a431",
          "md5": "ab878e918e9ab52b037b56e9ea974cf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.26.jar",
          "url": "gradle-0.1.26.jar",
          "size": 223895,
          "sha512": "42f67b73cf54eab7184095ce441e08cedf158249ff27c92b20d8656a4bef1e73f9d366aaaafb676586aa1999533218db0d769c7e359dd2f42e31608c0ebf9ea6",
          "sha256": "ec8fd76e1acccd6e293dc168707ed3e5f26138bbf74402a711a2dfaf05cc73a3",
          "sha1": "432a1094a8434351663ae8b203ef4734adf9a431",
          "md5": "ab878e918e9ab52b037b56e9ea974cf8"
        }
      ]
    }
  ]
}
