{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.34.jar",
          "url": "gradle-0.1.34.jar",
          "size": 243146,
          "sha512": "93d29cae3530fec48f92aa80660c0a8fa8b88f1813a5e4a3831a35bbdb5bcb34722cb41ccf735946ffd5de89eb92d4ebba73ce38daf62bb8d057c9ce45cf23e8",
          "sha256": "68832d20ffa9e3729416273f077e482c2567d9a064a39ca28ab1cf1b7c01bebc",
          "sha1": "2ecdd3e0886d4750ef1901ce049648a8a2991374",
          "md5": "664d815c6955944be79761587e790e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.34.jar",
          "url": "gradle-0.1.34.jar",
          "size": 243146,
          "sha512": "93d29cae3530fec48f92aa80660c0a8fa8b88f1813a5e4a3831a35bbdb5bcb34722cb41ccf735946ffd5de89eb92d4ebba73ce38daf62bb8d057c9ce45cf23e8",
          "sha256": "68832d20ffa9e3729416273f077e482c2567d9a064a39ca28ab1cf1b7c01bebc",
          "sha1": "2ecdd3e0886d4750ef1901ce049648a8a2991374",
          "md5": "664d815c6955944be79761587e790e00"
        }
      ]
    }
  ]
}
