{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.38.jar",
          "url": "gradle-0.1.38.jar",
          "size": 243173,
          "sha512": "b9016999c466e5f94dd6b8e9cb9fe58ca76d4323faa11851ec49efcf35cadc50b92a60f3a341987f5d8a2a52306e21ab68a20497462fdf29ca9f5ab95f7d7a56",
          "sha256": "f2d3a72d494fbcaae0bb6080a9ffcda75675ac67964c6d6484ba900591f9d861",
          "sha1": "53d53f0e3df96cfe66207db67113476e3f33ef61",
          "md5": "dcfbf6aa35d075be98a8877a71e2a228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250517"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.33"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.38.jar",
          "url": "gradle-0.1.38.jar",
          "size": 243173,
          "sha512": "b9016999c466e5f94dd6b8e9cb9fe58ca76d4323faa11851ec49efcf35cadc50b92a60f3a341987f5d8a2a52306e21ab68a20497462fdf29ca9f5ab95f7d7a56",
          "sha256": "f2d3a72d494fbcaae0bb6080a9ffcda75675ac67964c6d6484ba900591f9d861",
          "sha1": "53d53f0e3df96cfe66207db67113476e3f33ef61",
          "md5": "dcfbf6aa35d075be98a8877a71e2a228"
        }
      ]
    }
  ]
}
