{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "hide-internal-api",
    "version": "0.1.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.45.jar",
          "url": "hide-internal-api-0.1.45.jar",
          "size": 7174,
          "sha512": "24ebffe55d63f78e8e419d1ee89d3c21fb3b68afc2cd4858f87f87624561511d1fb3f3460ce137966f6df4d4a899e80ad142765c233cadaa1dab6eb012b90dd2",
          "sha256": "96b9c09765e210640d77f09c50dcb89e6b4a8dcbd39e945ea86e840938250423",
          "sha1": "eb567dec624eac18f909246bf7e86cdab6e10235",
          "md5": "046c2fdc21bb9512573ad77b93553249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "hide-internal-api-0.1.45.jar",
          "url": "hide-internal-api-0.1.45.jar",
          "size": 7174,
          "sha512": "24ebffe55d63f78e8e419d1ee89d3c21fb3b68afc2cd4858f87f87624561511d1fb3f3460ce137966f6df4d4a899e80ad142765c233cadaa1dab6eb012b90dd2",
          "sha256": "96b9c09765e210640d77f09c50dcb89e6b4a8dcbd39e945ea86e840938250423",
          "sha1": "eb567dec624eac18f909246bf7e86cdab6e10235",
          "md5": "046c2fdc21bb9512573ad77b93553249"
        }
      ]
    }
  ]
}
