{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "code-provider-generator",
    "version": "0.1.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "code-provider-generator-0.1.42.jar",
          "url": "code-provider-generator-0.1.42.jar",
          "size": 100930,
          "sha512": "f7aaee4e092e0f5b1200d140f21fc0ce3740144a2f529fba830826e742428d9dcd53b340c518a544889b46b0fa11a8cca75155ccd74ad3ab57763758836e0d4d",
          "sha256": "a7b1248890e550b33fee871a50fd0ca72809afeab576fd8146ea066d29c178bf",
          "sha1": "b50330c158014934f18f4ac0eb33780f94b4b077",
          "md5": "7404cc917b43bb698ad7da9da18703c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.2.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.2.0-Beta"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.redundent",
          "module": "kotlin-xml-builder",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "code-provider-generator-0.1.42.jar",
          "url": "code-provider-generator-0.1.42.jar",
          "size": 100930,
          "sha512": "f7aaee4e092e0f5b1200d140f21fc0ce3740144a2f529fba830826e742428d9dcd53b340c518a544889b46b0fa11a8cca75155ccd74ad3ab57763758836e0d4d",
          "sha256": "a7b1248890e550b33fee871a50fd0ca72809afeab576fd8146ea066d29c178bf",
          "sha1": "b50330c158014934f18f4ac0eb33780f94b4b077",
          "md5": "7404cc917b43bb698ad7da9da18703c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-provider-generator-0.1.42-sources.jar",
          "url": "code-provider-generator-0.1.42-sources.jar",
          "size": 24763,
          "sha512": "2e9c9eef25f872be08584412c33296571dbda3d405f049639666d579d5532fe57e10bbf2cb82dfbbd8728c55a088a1cef91ddb5e6940aaa9792b5e508838a9a7",
          "sha256": "777febf34869d7d48c989390dc0a2648672751928adf907b498b268647e598be",
          "sha1": "11a72650078200372f81de57ae5022e1317ab4d9",
          "md5": "6f594e8d653d9624b23d75c7a61de435"
        }
      ]
    }
  ]
}
