{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.25.jar",
          "url": "gradle-0.1.25.jar",
          "size": 223898,
          "sha512": "37e4517e867243c95972627c8c2c4c386776b9514176266d485ed9270adadfe066c6a308693c3a552bff3a234a4c80a2c514ee2434906bebb87790e9bc174526",
          "sha256": "8e1bd8a7ca7eb40a13dbfc9c75720edd87d5ff2c3b98084da86a04dda81c3753",
          "sha1": "51f9749684fbaeea5912fae8880f37add47a8dee",
          "md5": "240be50fad18a1beffca9805aeba69d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.1.0-Beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.25.jar",
          "url": "gradle-0.1.25.jar",
          "size": 223898,
          "sha512": "37e4517e867243c95972627c8c2c4c386776b9514176266d485ed9270adadfe066c6a308693c3a552bff3a234a4c80a2c514ee2434906bebb87790e9bc174526",
          "sha256": "8e1bd8a7ca7eb40a13dbfc9c75720edd87d5ff2c3b98084da86a04dda81c3753",
          "sha1": "51f9749684fbaeea5912fae8880f37add47a8dee",
          "md5": "240be50fad18a1beffca9805aeba69d6"
        }
      ]
    }
  ]
}
