{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test.dokka",
    "module": "custom-link",
    "version": "0.1.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.20.jar",
          "url": "custom-link-0.1.20.jar",
          "size": 5952,
          "sha512": "6aba15f7be62f519f5550f51a3f70145b113e4801fd1606380c6cc2dce466de8a33f9307434fdf34a709576a8a1b9e7dcfff86c17032b4c0aa1bffaee86aa8cd",
          "sha256": "7f2238507239ab123d16445bacc57d2344a3cb4472c3828481d0f820e43169b2",
          "sha1": "d6481017dbc22be50f90fd26f0ea4587fc2887f2",
          "md5": "30713aefdd754f4cc059a7974c897154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "custom-link-0.1.20.jar",
          "url": "custom-link-0.1.20.jar",
          "size": 5952,
          "sha512": "6aba15f7be62f519f5550f51a3f70145b113e4801fd1606380c6cc2dce466de8a33f9307434fdf34a709576a8a1b9e7dcfff86c17032b4c0aa1bffaee86aa8cd",
          "sha256": "7f2238507239ab123d16445bacc57d2344a3cb4472c3828481d0f820e43169b2",
          "sha1": "d6481017dbc22be50f90fd26f0ea4587fc2887f2",
          "md5": "30713aefdd754f4cc059a7974c897154"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-link-0.1.20-sources.jar",
          "url": "custom-link-0.1.20-sources.jar",
          "size": 1767,
          "sha512": "80526f40c8bed007c2d1a526805fe2672d41a5feaa7b7597c63bb28d8fa9b2303d2b623fc1d84c825d18c70f60241581f641cc931e14e2ebf730ce9585791d6b",
          "sha256": "76f56c2eb0d448ac2cd9b70820bcdbdd737857b47536fa06c1d38d64c535f4d7",
          "sha1": "464f038ceedbe3b98c084fd0491f21d9096db997",
          "md5": "8ea99bbf050e8f9667db5c7556bfd267"
        }
      ]
    }
  ]
}
