{
  "formatVersion": "1.1",
  "component": {
    "group": "com.m8test",
    "module": "gradle",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.21.jar",
          "url": "gradle-0.1.21.jar",
          "size": 261152,
          "sha512": "751ca7ad8f4bb93d2287b5422ea8daf3689556f30c105cec3a2a386aa71ddda4d9c0c8121ee30597c8fcdac266145c1c7fc203e40cef3e634b50ce3ef42d8eb6",
          "sha256": "498096da808262d5d31aae754c761e90a2909a4084f6c2c3b69516f1f21b420e",
          "sha1": "599ae1b5c43ac2f0ae3058d2d4912cb681a5262c",
          "md5": "039664f68a3c72421f1167dcacbe0611"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin.plugin.serialization",
          "module": "org.jetbrains.kotlin.plugin.serialization.gradle.plugin",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20250107"
          }
        },
        {
          "group": "de.femtopedia.dex2jar",
          "module": "dex2jar",
          "version": {
            "requires": "2.4.28"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.21.jar",
          "url": "gradle-0.1.21.jar",
          "size": 261152,
          "sha512": "751ca7ad8f4bb93d2287b5422ea8daf3689556f30c105cec3a2a386aa71ddda4d9c0c8121ee30597c8fcdac266145c1c7fc203e40cef3e634b50ce3ef42d8eb6",
          "sha256": "498096da808262d5d31aae754c761e90a2909a4084f6c2c3b69516f1f21b420e",
          "sha1": "599ae1b5c43ac2f0ae3058d2d4912cb681a5262c",
          "md5": "039664f68a3c72421f1167dcacbe0611"
        }
      ]
    }
  ]
}
